Frax.io | Chainlink Hackathon 2021
ipfs/community pull request #482
Opened 2021-04-18 05:10 UTC by stereoIII6

NFT & Gaming Prize Winners

2021-04-20 18:59 UTC, autonome commented on templates/project-submission-template.md
> -GitHub Discussion: <!--Start a disucssion with the community here: https://github.com/filecoin-project/community/discussions/new and attach the link!-->
Can you create a discussion topic per the instructions below, and update the PR? thanks!

https://github.com/ipfs/community/#ecosystem-projects

2021-04-20 20:54 UTC, stereoIII6 commented
hey ...

thnx for your feedback ... it will be fixed by tomorrow

On Tue, 20 Apr 2021, 21:00 Dietrich Ayala, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi Frax team! Great to have you. A few changes needed below.
> ------------------------------
>
> In templates/project-submission-template.md
> <https://github.com/ipfs/community/pull/482#discussion_r616956528>:
>
> >
>  ## Github repo
> -<!--Attach a link to your GitHub repo if it's OSS-->
> +https://github.com/FraxioOfficial
>
> Hi! The repo appears empty, is the code somewhere there?
> ------------------------------
>
> In templates/project-submission-template.md
> <https://github.com/ipfs/community/pull/482#discussion_r616958071>:
>
> >
> -## How the community can engage
> -GitHub Discussion: <!--Start a disucssion with the community here: https://github.com/filecoin-project/community/discussions/new and attach the link!-->
>
> Can you create a discussion topic per the instructions below, and update
> the PR? thanks!
>
> https://github.com/ipfs/community/#ecosystem-projects
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipfs/community/pull/482#pullrequestreview-640322971>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIEO2XOPDG6O73QJZQ4S4UDTJXFM3ANCNFSM43D2KDOQ>
> .
>

2021-04-20 23:27 UTC, stereoIII6 commented on templates/project-submission-template.md
> +https://github.com/FraxioOfficial
Hi @autonome ... 

Yes the Demo version is in the Pye Editor

https://github.com/FraxioOfficial/pye_editor

We have a docs repo that is currently being built 

https://github.com/FraxioOfficial/fraxio_docs

and the final project repo is 

https://github.com/FraxioOfficial/fraxio_framework

but this one is still empty at the moment !

2021-04-20 23:34 UTC, stereoIII6 commented
We are planning to run our own IPFS Node and also Pinning Service ...

We are still reading into the technical Details ...
is there a out of the box tutorial anywhere ?

We also need a IPFS Directory Structure for every Client that looks somewhat like :

-Client By Address 
-- PYE Token By ID
--- Image
--- Image
--- Image

2021-04-22 15:30 UTC, autonome requested changes
just need discussion thread and can merge!

2021-04-22 15:30 UTC, autonome commented on templates/project-submission-template.md
> -* GitHub Discussion: <!--Start a discussion with the community here: https://github.com/ipfs/community/discussions/new and attach the link!-->
Please start a show-and-tell thread on the discussion board and link here

2021-04-22 17:48 UTC, autonome commented
> We are planning to run our own IPFS Node and also Pinning Service ...
> 
> We are still reading into the technical Details ...
> is there a out of the box tutorial anywhere ?

You can see a pinning service example implementation here:

https://github.com/ipfs-shipyard/rb-pinning-service-api

> We also need a IPFS Directory Structure for every Client that looks somewhat like :
> 
> -Client By Address
> -- PYE Token By ID
> --- Image
> --- Image
> --- Image

Sure, you can create that structure and then add the root folders to IPFS.

2021-04-22 17:49 UTC, autonome commented
I think just waiting on a discussion thread to be created, per the instructions here: https://github.com/ipfs/community#ecosystem-projects

2021-04-22 20:28 UTC, RIPMyLife commented
Woo fract.io is amazing

2021-04-22 20:48 UTC, 1rvinC commented
> > We are planning to run our own IPFS Node and also Pinning Service ...
> > We are still reading into the technical Details ...
> > is there a out of the box tutorial anywhere ?
> 
> You can see a pinning service example implementation here:
> 
> https://github.com/ipfs-shipyard/rb-pinning-service-api
> 
> > We also need a IPFS Directory Structure for every Client that looks somewhat like :
> > -Client By Address
> > -- PYE Token By ID
> > --- Image
> > --- Image
> > --- Image
> 
> Sure, you can create that structure and then add the root folders to IPFS.

Thanks for the help!

2021-04-25 18:35 UTC, autonome commented
Hey all, the content looks ready now, thanks for making the changes.

However, you have modified *the template*. You need to take the final file, and create a *new file* in the `projects` directory, named with your project. eg: `frax.md`

You can see the others here:

https://github.com/ipfs/community/tree/master/projects

It might be easier to start a new pull request with the completed file.

2021-05-08 17:10 UTC, autonome commented
redone in #531

2021-05-08 17:10 UTC, closed without merging

2021-05-08 17:10 UTC, autonome commented
redone in #531

2021-05-08 23:05 UTC, Alchemist21 commented
Hi @autonome. We are new in github and wanted to know how to make a pull request and be included in the master project? Thank you