[PROJECT SUBMISSION] ipfs-cidcli
ipfs/community pull request #600
Opened 2021-06-27 19:37 UTC by acul71

Create a project profile here in the ipfs/community repository using the project submission template here. Name the file name after your project and fill in as much information as you can. Use your project name as the file name so the community can find your project easily!

2021-06-27 19:42 UTC, acul71 commented on templates/project-submission-template.md
> +Go to https://github.com/acul71/ipfs-cidsail and follow instruction to install. Check the app and report any bugs/anomalies opening an issue
https://github.com/ipfs/community/discussions/601

2021-06-27 19:51 UTC, acul71 commented on templates/project-submission-template.md
> +Go to https://github.com/acul71/ipfs-cidsail and follow instruction to install. Check the app and report any bugs/anomalies opening an issue
https://github.com/ipfs/community/discussions/601

2021-06-28 20:32 UTC, autonome requested changes
Hi, you have modified the submission template. You must instead create a *new* file in the `projects` directory.

2021-06-28 23:04 UTC, acul71 commented
Create ipfs-cidsail.md #602

2021-06-29 02:27 UTC, closed without merging