Update security section of CONTRIBUTING.md
ipfs/community pull request #772
Opened 2023-03-13 15:00 UTC by AnomalRoil

To mention how abuse reports should be routed.

2023-05-02 14:59 UTC, mishmosh approved these changes

2023-05-03 21:35 UTC, ElPaisano requested changes
Hi team, I'm one of the docs writers who originally escalated this issue. Thank you for working on this.

I'm suggesting changes to the copy before this is merged.

2023-05-03 21:35 UTC, ElPaisano commented on CONTRIBUTING.md
> +Note that **abuse reports** (e.g. if IPFS is used to host malware, questionnable content or for phishing purposes) should be reported to abuse@ipfs.tech instead.
Fixes spelling, wording, adds mailto link

```suggestion
> Report **IPFS abuse** (e.g. using IPFS for the malware hosting, distribution of questionable content, phishing purposes, etc.) to [abuse@ipfs.tech](mailto:abuse@ipfs.tech).
```

2023-05-04 08:46 UTC, AnomalRoil commented
I have now also added a "Security Policy", so that it would be displayed when people create new issues, since it seems that a lot of recent issues are related to spam / abuse:
![image](https://user-images.githubusercontent.com/10077203/236155158-777e73a1-4a36-4d45-bbbc-27de783adb8a.png)

2023-05-05 06:25 UTC, BigLep reviewed
I added some language to be even more precise I hope.  I think this can merged if you agree with the suggestions.

(This whole PR speaks to the need though that the ipfs.io HTTP gateway product needs to have a self-service discoverable way for consumers to learn about it.  We should be pointing people there and letting ipfs.io HTTP gateway docs discuss abuse@ipfs.tech.  Having an ipfs.io HTTP gateway landing page is being discussed in https://filecoinproject.slack.com/archives/C03FPDYG6T0/p1682646043077979 (private FIL slack thread).)

2023-05-05 06:25 UTC, BigLep commented on CONTRIBUTING.md
> +> Note that IPFS isn't responsible for gateways, therefor report **IPFS abuse** (e.g. using IPFS for malware hosting, distribution of questionable content, phishing purposes, etc.) to their respectiv
```suggestion
> Note that the IPFS project is much more than an [HTTP Gateway](https://docs.ipfs.tech/concepts/ipfs-gateway/) at https://ipfs.io/ipfs.  The ipfs.io gateway is a "common good" product in the IPFS ecosystem.  Therefore report **TTP gateway abuse** (e.g. using an HTTP gateway for malware hosting, distribution of questionable content, phishing purposes, etc.) to their respective HTTP gateway owners. If you've seen abusive material distributed through ipfs.io, please report it to [abuse@ipfs.tech](mailto:abuse@ipfs.tech).  See our [Security Policy](SECURITY.md) for more details.
```

2023-05-05 06:25 UTC, BigLep commented on SECURITY.md
> +The IPFS protocol and its implementations are still in heavy development. This means that there may be problems in our protocols, or there may be mistakes in our implementations. And -- though IPFS i
```suggestion
The IPFS protocol and its implementations are in varying but active levels of development. This means that there may be problems in our protocols, or there may be mistakes in our implementations. We take security vulnerabilities very seriously. If you discover a security issue, please bring it to our attention right away!
```

2023-05-05 06:25 UTC, BigLep commented on SECURITY.md
> +If you find a vulnerability that may affect live deployments -- for example, expose a remote execution exploit -- please send your report privately to security@ipfs.io, please DO NOT file a public is
```suggestion
If you find a vulnerability that may affect live deployments -- for example, expose a remote execution exploit -- please send your report privately to either:
1. The implementation team if its an issue with a particular implementation OR
2. security@ipfs.tech if you're not sure or if its an underlying issue with an IPFS protocol.
Please DO NOT file a public issue.
```

2023-05-05 06:25 UTC, BigLep commented on SECURITY.md
> +While IPFS is a modular suite of protocols for organizing and transferring data, we have seen a lot of people willing to report **IPFS usage for abuse** (e.g. using IPFS for malware hosting, distribu
```suggestion
While [IPFS is a stack of protocols and tools for moving content-addressed data](https://specs.ipfs.tech/architecture/principles/), there is often confusion about one particular manifestation of IPFS in [HTTP Gateways](https://docs.ipfs.tech/concepts/ipfs-gateway/) like https://ipfs.io/ipfs.  We have seen a lot of reports about **abuse 
 from these IPFS gateways** (e.g. using an HTTP gateway for malware hosting, distributing questionable content, phishing purposes, etc.).  These should be reported directly to the HTTP gateway product that provides the data.
```

2023-05-05 06:25 UTC, BigLep commented on SECURITY.md
> +So, to report abuse about ipfs.io, please send an email to [abuse@ipfs.tech](mailto:abuse@ipfs.tech) and do not open an issue here, since IPFS as a community is not the same as the ipfs.io gateway.
```suggestion
To report abuse about the ipfs.io HTTP gateway, please send an email to [abuse@ipfs.tech](mailto:abuse@ipfs.tech).  Do not open an issue here since IPFS as a community and project is not the same as the ipfs.io HTTP gateway.
```

2023-05-05 07:54 UTC, AnomalRoil commented
@BigLep The ipfs.io landing page has a "help" section that discuss abuse already. But it seems people google IPFS and land here.

2023-05-05 07:56 UTC, AnomalRoil commented on CONTRIBUTING.md
> +> Note that the IPFS project is much more than an [HTTP Gateway](https://docs.ipfs.tech/concepts/ipfs-gateway/) at https://ipfs.io/ipfs.  The ipfs.io gateway is a "common good" product in the IPFS ec
```suggestion
> Note that the IPFS project is much more than an [HTTP Gateway](https://docs.ipfs.tech/concepts/ipfs-gateway/) at https://ipfs.io/ipfs.  The ipfs.io gateway is a "common good" product in the IPFS ecosystem.  Therefore report **HTTP gateway abuse** (e.g. using an HTTP gateway for malware hosting, distribution of questionable content, phishing purposes, etc.) to their respective HTTP gateway owners. If you've seen abusive material distributed through ipfs.io, please report it to [abuse@ipfs.tech](mailto:abuse@ipfs.tech).  See our [Security Policy](SECURITY.md) for more details.
```

2023-05-05 11:09 UTC, cewood commented on SECURITY.md
> +To report abuse about the ipfs.io HTTP gateway, please send an email to [abuse@ipfs.tech](mailto:abuse@ipfs.tech).  Do not open an issue here since IPFS as a community and project is not the same as
```suggestion
To report abuse about the ipfs.io HTTP gateway, please send an email to [abuse@ipfs.tech](mailto:abuse@ipfs.tech).  Do not open an issue here since IPFS is a community project, and is not the same as the ipfs.io HTTP gateway.
```

2023-05-05 17:54 UTC, BigLep approved these changes
Thanks for taking action to make things better!

2023-05-05 17:55 UTC, merged